[2024-11-22 05:44:24,141] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-22T05:43:16.232026+00:00 [queued]>
[2024-11-22 05:44:24,180] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-22T05:43:16.232026+00:00 [queued]>
[2024-11-22 05:44:24,181] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-11-22 05:44:24,181] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-11-22 05:44:24,182] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-11-22 05:44:24,261] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22T05:43:16.232026+00:00
[2024-11-22 05:44:24,266] {standard_task_runner.py:52} INFO - Started process 2168 to run task
[2024-11-22 05:44:24,269] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'kpi_calculation_pipeline', 'fetch_data', '2024-11-22T05:43:16.232026+00:00', '--job-id', '288', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/data_injestion_dag/bazefield_kpi_calculation.py', '--cfg-path', '/tmp/tmpjjnkqz0z', '--error-file', '/tmp/tmpogxqpze0']
[2024-11-22 05:44:24,271] {standard_task_runner.py:77} INFO - Job 288: Subtask fetch_data
[2024-11-22 05:44:24,399] {logging_mixin.py:104} INFO - Running <TaskInstance: kpi_calculation_pipeline.fetch_data 2024-11-22T05:43:16.232026+00:00 [running]> on host 1b505405454d
[2024-11-22 05:44:24,579] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=kpi_calculation_pipeline
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-22T05:43:16.232026+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-22T05:43:16.232026+00:00
[2024-11-22 05:44:24,591] {logging_mixin.py:104} INFO - fetching api data between 2024-11-22T10:00:00+05:30Z and 2024-11-22T10:59:59+05:30Z
[2024-11-22 05:44:24,610] {base.py:69} INFO - Using connection to: id: bazefield_api. Host: https://idcc.jsw.in, Port: None, Schema: , Login: , Password: None, extra: {'Authorization': '***'}
[2024-11-22 05:44:24,613] {http.py:140} INFO - Sending 'GET' to url: https://idcc.jsw.in/Bazefield.Services/api/objects/timeseries/aggregated?objectIds=11002CC087CEB000,11003170EE0EB000,11003170FD4EB000,110031710ACEB000,110031717B8EB000,11003171B24EB000,11003171C00EB000,11003171DD8EB000,11003171EB8EB000,110031733E0EB000,110031734C4EB000,110031735B4EB000,11003176A54EB000,11003177284EB000,1100317739CEB000,110031720D0EB000,11003173790EB000,11003173A68EB000,110031758CCEB000,11003176424EB000,11003176520EB000,11003176620EB000,11003176834EB000,11003173004EB000,110031730FCEB000,11003175A08EB000,11003175C24EB000,11003175D24EB000,11003175E94EB000,11003175FB4EB000,11003176324EB000,110031775B8EB000,11003171260EB000,11003171344EB000,11003171438EB000,11003171520EB000,11003171608EB000,110031716F0EB000,1100317188CEB000,11003171960EB000,11003171A48EB000,11003171CF0EB000,11003171FF0EB000,1100317369CEB000,110031723ACEB000,11003172488EB000,1100317257CEB000,11003172664EB000,11003172750EB000,1100317283CEB000,11003172928EB000,11003175B1CEB000,11003176724EB000,11003176938EB000,110031774A8EB000,110031721D0EB000,110031722CCEB000,11003172A20EB000,11003172B08EB000,11003172BFCEB000,11003173894EB000,11003173988EB000,1100317621CEB000,11003176C94EB000,11003176DCCEB000,11003177174EB000,11003172CE4EB000,11003172DD8EB000,11003172F0CEB000,11003173B58EB000,11003173C54EB000,11003173D50EB000,11003174760EB000,11003175698EB000,11003176B68EB000,11003176F14EB000,1100317705CEB000,11003174B6CEB000,11003175278EB000,11003175374EB000,110031755A0EB000,11003173F2CEB000,11003174C68EB000,11003174D68EB000,11003174F64EB000,11003175060EB000,11003175178EB000,11003175480EB000,110031760C4EB000,11003173E34EB000,11003174030EB000,11003174660EB000,1100317487CEB000,11003174978EB000,11003174A7CEB000,110031731F0EB000,110031732F0EB000,1100317411CEB000,11003174214EB000,11003174324EB000,1100317443CEB000,11003174544EB000,11003174E6CEB000,110031757B4EB000&points=ActivePower&aggregates=TIMEAVERAGE&from=2024-11-22T10:00:00+05:30Z&to=2024-11-22T10:59:59+05:30Z&interval=10m&format=json
[2024-11-22 05:44:25,869] {http.py:154} ERROR - HTTP error: FormatException
[2024-11-22 05:44:25,872] {http.py:155} ERROR - {"responseStatus":{"errorCode":"FormatException","message":"String '2024-11-22t10:00:00 05:30z' was not recognized as a valid DateTime.","errors":[]}}
[2024-11-22 05:44:25,874] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 152, in check_response
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: FormatException for url: https://idcc.jsw.in/Bazefield.Services/api/objects/timeseries/aggregated?objectIds=11002CC087CEB000,11003170EE0EB000,11003170FD4EB000,110031710ACEB000,110031717B8EB000,11003171B24EB000,11003171C00EB000,11003171DD8EB000,11003171EB8EB000,110031733E0EB000,110031734C4EB000,110031735B4EB000,11003176A54EB000,11003177284EB000,1100317739CEB000,110031720D0EB000,11003173790EB000,11003173A68EB000,110031758CCEB000,11003176424EB000,11003176520EB000,11003176620EB000,11003176834EB000,11003173004EB000,110031730FCEB000,11003175A08EB000,11003175C24EB000,11003175D24EB000,11003175E94EB000,11003175FB4EB000,11003176324EB000,110031775B8EB000,11003171260EB000,11003171344EB000,11003171438EB000,11003171520EB000,11003171608EB000,110031716F0EB000,1100317188CEB000,11003171960EB000,11003171A48EB000,11003171CF0EB000,11003171FF0EB000,1100317369CEB000,110031723ACEB000,11003172488EB000,1100317257CEB000,11003172664EB000,11003172750EB000,1100317283CEB000,11003172928EB000,11003175B1CEB000,11003176724EB000,11003176938EB000,110031774A8EB000,110031721D0EB000,110031722CCEB000,11003172A20EB000,11003172B08EB000,11003172BFCEB000,11003173894EB000,11003173988EB000,1100317621CEB000,11003176C94EB000,11003176DCCEB000,11003177174EB000,11003172CE4EB000,11003172DD8EB000,11003172F0CEB000,11003173B58EB000,11003173C54EB000,11003173D50EB000,11003174760EB000,11003175698EB000,11003176B68EB000,11003176F14EB000,1100317705CEB000,11003174B6CEB000,11003175278EB000,11003175374EB000,110031755A0EB000,11003173F2CEB000,11003174C68EB000,11003174D68EB000,11003174F64EB000,11003175060EB000,11003175178EB000,11003175480EB000,110031760C4EB000,11003173E34EB000,11003174030EB000,11003174660EB000,1100317487CEB000,11003174978EB000,11003174A7CEB000,110031731F0EB000,110031732F0EB000,1100317411CEB000,11003174214EB000,11003174324EB000,1100317443CEB000,11003174544EB000,11003174E6CEB000,110031757B4EB000&points=ActivePower&aggregates=TIMEAVERAGE&from=2024-11-22T10:00:00+05:30Z&to=2024-11-22T10:59:59+05:30Z&interval=10m&format=json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/data_injestion_dag/bazefield_kpi_calculation.py", line 268, in fetch_active_power_kpi
    query_string = '&'.join(f"{key}={value}" for key, value in params.items())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 141, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 198, in run_and_check
    self.check_response(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/hooks/http.py", line 156, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 400:FormatException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_injestion_dag/bazefield_kpi_calculation.py", line 273, in fetch_active_power_kpi
    data = response.json()
ValueError: Error fetching data from API: 400:FormatException
[2024-11-22 05:44:25,893] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=kpi_calculation_pipeline, task_id=fetch_data, execution_date=20241122T054316, start_date=20241122T054424, end_date=20241122T054425
[2024-11-22 05:44:26,046] {local_task_job.py:151} INFO - Task exited with return code 1
